/* ==========================================================================
   NICA ENGLISH CLUB — EVERYDAY ENGLISH
   data.js — 100 Everyday English Verbs & Expressions
   Schema per expression:
   id, expression, forms:{present,third,past,pastParticiple,ing},
   visualization, interpretation, example, category, difficulty
   categories: morning | house | moving | food | work | conversation | natural
   ========================================================================== */

const CATEGORIES = [
  { id: "all", label: "All", icon: "🧠" },
  { id: "morning", label: "Morning & Getting Ready", icon: "🌅" },
  { id: "house", label: "Around the House", icon: "🏠" },
  { id: "moving", label: "Moving Around", icon: "🚶" },
  { id: "food", label: "Food & Daily Life", icon: "🍔" },
  { id: "work", label: "Work & School", icon: "💼" },
  { id: "conversation", label: "Everyday Conversation", icon: "📱" },
  { id: "natural", label: "Very Natural Everyday English", icon: "🔥" }
];

const EXPRESSIONS = [
  // ===================== MORNING & GETTING READY (1-20) =====================
  { id: 1, expression: "wake up", forms: { present: "wake up", third: "wakes up", past: "woke up", pastParticiple: "woken up", ing: "waking up" },
    visualization: "You're sleeping. Your eyes open and you are no longer asleep.",
    interpretation: "Despertarse.", example: "I wake up at 6 every day.",
    category: "morning", difficulty: "easy" },
  { id: 2, expression: "get up", forms: { present: "get up", third: "gets up", past: "got up", pastParticiple: "gotten up", ing: "getting up" },
    visualization: "You're lying in bed and you leave the bed by standing up.",
    interpretation: "Levantarse de la cama.", example: "I don't get up right after I wake up.",
    category: "morning", difficulty: "easy" },
  { id: 3, expression: "take a shower", forms: { present: "take a shower", third: "takes a shower", past: "took a shower", pastParticiple: "taken a shower", ing: "taking a shower" },
    visualization: "You go into the shower and water starts falling over your body.",
    interpretation: "Ducharse.", example: "I take a shower before breakfast.",
    category: "morning", difficulty: "easy" },
  { id: 4, expression: "dry off", forms: { present: "dry off", third: "dries off", past: "dried off", pastParticiple: "dried off", ing: "drying off" },
    visualization: "You come out of the shower wet and use a towel until your body is dry.",
    interpretation: "Secarse.", example: "I dry off quickly because the bathroom is cold.",
    category: "morning", difficulty: "medium" },
  { id: 5, expression: "get dressed", forms: { present: "get dressed", third: "gets dressed", past: "got dressed", pastParticiple: "gotten dressed", ing: "getting dressed" },
    visualization: "You're getting ready in the morning. You're putting your clothes on.",
    interpretation: "Prepararte / ponerte la ropa.", example: "I usually get dressed before breakfast.",
    category: "morning", difficulty: "easy" },
  { id: 6, expression: "put on my shirt", forms: { present: "put on my shirt", third: "puts on my shirt", past: "put on my shirt", pastParticiple: "put on my shirt", ing: "putting on my shirt" },
    visualization: "You take your shirt and put your head and arms through it.",
    interpretation: "Ponerme la camisa.", example: "I put on my shirt before I put on my pants.",
    category: "morning", difficulty: "easy" },
  { id: 7, expression: "put on my shoes", forms: { present: "put on my shoes", third: "puts on my shoes", past: "put on my shoes", pastParticiple: "put on my shoes", ing: "putting on my shoes" },
    visualization: "You put your shoes onto your feet before going outside.",
    interpretation: "Ponerme los zapatos.", example: "I put on my shoes right before I leave.",
    category: "morning", difficulty: "easy" },
  { id: 8, expression: "tie my shoes", forms: { present: "tie my shoes", third: "ties my shoes", past: "tied my shoes", pastParticiple: "tied my shoes", ing: "tying my shoes" },
    visualization: "You bend down and make the knots on your shoes.",
    interpretation: "Amarrarme los zapatos.", example: "I always tie my shoes twice so they don't come loose.",
    category: "morning", difficulty: "medium" },
  { id: 9, expression: "take off my shoes", forms: { present: "take off my shoes", third: "takes off my shoes", past: "took off my shoes", pastParticiple: "taken off my shoes", ing: "taking off my shoes" },
    visualization: "You arrive home and remove your shoes from your feet.",
    interpretation: "Quitarme los zapatos.", example: "I take off my shoes as soon as I get home.",
    category: "morning", difficulty: "easy" },
  { id: 10, expression: "comb my hair", forms: { present: "comb my hair", third: "combs my hair", past: "combed my hair", pastParticiple: "combed my hair", ing: "combing my hair" },
    visualization: "You stand in front of a mirror and move a comb through your hair.",
    interpretation: "Peinarme.", example: "I comb my hair after I take a shower.",
    category: "morning", difficulty: "easy" },
  { id: 11, expression: "brush my teeth", forms: { present: "brush my teeth", third: "brushes my teeth", past: "brushed my teeth", pastParticiple: "brushed my teeth", ing: "brushing my teeth" },
    visualization: "You stand in front of the mirror and move a toothbrush around your teeth.",
    interpretation: "Cepillarme los dientes.", example: "I brush my teeth twice a day.",
    category: "morning", difficulty: "easy" },
  { id: 12, expression: "wash my face", forms: { present: "wash my face", third: "washes my face", past: "washed my face", pastParticiple: "washed my face", ing: "washing my face" },
    visualization: "You put water on your face and clean it with your hands.",
    interpretation: "Lavarme la cara.", example: "I wash my face right after I wake up.",
    category: "morning", difficulty: "easy" },
  { id: 13, expression: "shave", forms: { present: "shave", third: "shaves", past: "shaved", pastParticiple: "shaved", ing: "shaving" },
    visualization: "You use a razor or electric shaver to remove hair from your face.",
    interpretation: "Afeitarse.", example: "I shave every other day.",
    category: "morning", difficulty: "easy" },
  { id: 14, expression: "get ready", forms: { present: "get ready", third: "gets ready", past: "got ready", pastParticiple: "gotten ready", ing: "getting ready" },
    visualization: "You're doing everything you need to do before leaving or starting your day.",
    interpretation: "Alistarse / prepararse.", example: "It takes me 30 minutes to get ready.",
    category: "morning", difficulty: "easy" },
  { id: 15, expression: "set an alarm", forms: { present: "set an alarm", third: "sets an alarm", past: "set an alarm", pastParticiple: "set an alarm", ing: "setting an alarm" },
    visualization: "You use your phone to choose a time when you want the alarm to ring.",
    interpretation: "Poner una alarma.", example: "I set an alarm for 5:45 every night.",
    category: "morning", difficulty: "medium" },
  { id: 16, expression: "turn off the alarm", forms: { present: "turn off the alarm", third: "turns off the alarm", past: "turned off the alarm", pastParticiple: "turned off the alarm", ing: "turning off the alarm" },
    visualization: "Your alarm starts ringing and you touch your phone to stop it.",
    interpretation: "Apagar la alarma.", example: "I turn off the alarm and stay in bed for one more minute.",
    category: "morning", difficulty: "medium" },
  { id: 17, expression: "grab a coffee", forms: { present: "grab a coffee", third: "grabs a coffee", past: "grabbed a coffee", pastParticiple: "grabbed a coffee", ing: "grabbing a coffee" },
    visualization: "You quickly get a coffee before continuing with your day.",
    interpretation: "Tomar / conseguir un café rápido.", example: "I grab a coffee on my way to work.",
    category: "morning", difficulty: "medium" },
  { id: 18, expression: "have breakfast", forms: { present: "have breakfast", third: "has breakfast", past: "had breakfast", pastParticiple: "had breakfast", ing: "having breakfast" },
    visualization: "You sit down and eat your first meal of the day.",
    interpretation: "Desayunar.", example: "I have breakfast at 7 in the morning.",
    category: "morning", difficulty: "easy" },
  { id: 19, expression: "drink some water", forms: { present: "drink some water", third: "drinks some water", past: "drank some water", pastParticiple: "drunk some water", ing: "drinking some water" },
    visualization: "You pick up a glass or bottle and drink water.",
    interpretation: "Tomar / beber agua.", example: "I drink some water before I have coffee.",
    category: "morning", difficulty: "easy" },
  { id: 20, expression: "leave the house", forms: { present: "leave the house", third: "leaves the house", past: "left the house", pastParticiple: "left the house", ing: "leaving the house" },
    visualization: "You open the door, walk outside and close the door behind you.",
    interpretation: "Salir de casa.", example: "I leave the house at 7:30 every morning.",
    category: "morning", difficulty: "easy" },

  // ===================== AROUND THE HOUSE (21-40) =====================
  { id: 21, expression: "turn on the light", forms: { present: "turn on the light", third: "turns on the light", past: "turned on the light", pastParticiple: "turned on the light", ing: "turning on the light" },
    visualization: "You enter a dark room and press the light switch.",
    interpretation: "Encender la luz.", example: "I turn on the light when I walk into a dark room.",
    category: "house", difficulty: "easy" },
  { id: 22, expression: "turn off the light", forms: { present: "turn off the light", third: "turns off the light", past: "turned off the light", pastParticiple: "turned off the light", ing: "turning off the light" },
    visualization: "You leave the room and press the switch to make the room dark.",
    interpretation: "Apagar la luz.", example: "I always turn off the light before I go to sleep.",
    category: "house", difficulty: "easy" },
  { id: 23, expression: "turn on the tv", forms: { present: "turn on the tv", third: "turns on the tv", past: "turned on the tv", pastParticiple: "turned on the tv", ing: "turning on the tv" },
    visualization: "You pick up the remote and turn the television on.",
    interpretation: "Encender la tele.", example: "I turn on the TV to watch the news.",
    category: "house", difficulty: "easy" },
  { id: 24, expression: "turn off the tv", forms: { present: "turn off the tv", third: "turns off the tv", past: "turned off the tv", pastParticiple: "turned off the tv", ing: "turning off the tv" },
    visualization: "You're watching TV and press the button to stop it.",
    interpretation: "Apagar la tele.", example: "I turn off the TV before I go to bed.",
    category: "house", difficulty: "easy" },
  { id: 25, expression: "open the door", forms: { present: "open the door", third: "opens the door", past: "opened the door", pastParticiple: "opened the door", ing: "opening the door" },
    visualization: "You grab the handle and move the door so you can enter or leave.",
    interpretation: "Abrir la puerta.", example: "I open the door for my grandmother.",
    category: "house", difficulty: "easy" },
  { id: 26, expression: "close the door", forms: { present: "close the door", third: "closes the door", past: "closed the door", pastParticiple: "closed the door", ing: "closing the door" },
    visualization: "You push the door until it is completely closed.",
    interpretation: "Cerrar la puerta.", example: "Please close the door behind you.",
    category: "house", difficulty: "easy" },
  { id: 27, expression: "lock the door", forms: { present: "lock the door", third: "locks the door", past: "locked the door", pastParticiple: "locked the door", ing: "locking the door" },
    visualization: "You close the door and use a key or lock to secure it.",
    interpretation: "Poner llave a la puerta.", example: "I always lock the door before I go to bed.",
    category: "house", difficulty: "easy" },
  { id: 28, expression: "unlock the door", forms: { present: "unlock the door", third: "unlocks the door", past: "unlocked the door", pastParticiple: "unlocked the door", ing: "unlocking the door" },
    visualization: "You use a key or lock mechanism so the door can be opened.",
    interpretation: "Quitar el seguro a la puerta.", example: "I unlock the door with my keys every morning.",
    category: "house", difficulty: "easy" },
  { id: 29, expression: "pick up", forms: { present: "pick up", third: "picks up", past: "picked up", pastParticiple: "picked up", ing: "picking up" },
    visualization: "Something is on the floor and you bend down to lift it.",
    interpretation: "Recoger / levantar algo.", example: "I picked up my keys before I left.",
    category: "house", difficulty: "medium" },
  { id: 30, expression: "put it down", forms: { present: "put it down", third: "puts it down", past: "put it down", pastParticiple: "put it down", ing: "putting it down" },
    visualization: "You have something in your hand and place it on a surface.",
    interpretation: "Dejarlo / ponerlo sobre una superficie.", example: "I put it down on the table.",
    category: "house", difficulty: "medium" },
  { id: 31, expression: "clean up", forms: { present: "clean up", third: "cleans up", past: "cleaned up", pastParticiple: "cleaned up", ing: "cleaning up" },
    visualization: "Things are messy and you start picking them up and organizing the area.",
    interpretation: "Ordenar / limpiar el desorden.", example: "I need to clean up before my friends come over.",
    category: "house", difficulty: "medium" },
  { id: 32, expression: "throw away", forms: { present: "throw away", third: "throws away", past: "threw away", pastParticiple: "thrown away", ing: "throwing away" },
    visualization: "You have something you don't want anymore and put it in the trash.",
    interpretation: "Botar / tirar a la basura.", example: "I threw away the old food in the fridge.",
    category: "house", difficulty: "medium" },
  { id: 33, expression: "take out the trash", forms: { present: "take out the trash", third: "takes out the trash", past: "took out the trash", pastParticiple: "taken out the trash", ing: "taking out the trash" },
    visualization: "You take the full trash bag outside.",
    interpretation: "Sacar la basura.", example: "I take out the trash every Sunday night.",
    category: "house", difficulty: "medium" },
  { id: 34, expression: "do the laundry", forms: { present: "do the laundry", third: "does the laundry", past: "did the laundry", pastParticiple: "done the laundry", ing: "doing the laundry" },
    visualization: "You have dirty clothes and wash them in a washing machine.",
    interpretation: "Lavar la ropa.", example: "I do the laundry on the weekend.",
    category: "house", difficulty: "easy" },
  { id: 35, expression: "hang up the clothes", forms: { present: "hang up the clothes", third: "hangs up the clothes", past: "hung up the clothes", pastParticiple: "hung up the clothes", ing: "hanging up the clothes" },
    visualization: "You take clothes and place them on a clothesline or hanger.",
    interpretation: "Colgar la ropa.", example: "I hang up the clothes to dry after I wash them.",
    category: "house", difficulty: "medium" },
  { id: 36, expression: "fold the clothes", forms: { present: "fold the clothes", third: "folds the clothes", past: "folded the clothes", pastParticiple: "folded the clothes", ing: "folding the clothes" },
    visualization: "You take clean clothes and fold them neatly.",
    interpretation: "Doblar la ropa.", example: "I fold the clothes while I watch TV.",
    category: "house", difficulty: "easy" },
  { id: 37, expression: "put away", forms: { present: "put away", third: "puts away", past: "put away", pastParticiple: "put away", ing: "putting away" },
    visualization: "You take something and return it to its usual place.",
    interpretation: "Guardar en su lugar.", example: "I put away the dishes after they dry.",
    category: "house", difficulty: "medium" },
  { id: 38, expression: "clean the house", forms: { present: "clean the house", third: "cleans the house", past: "cleaned the house", pastParticiple: "cleaned the house", ing: "cleaning the house" },
    visualization: "You move around the house cleaning and organizing different areas.",
    interpretation: "Limpiar la casa.", example: "I clean the house every Saturday.",
    category: "house", difficulty: "easy" },
  { id: 39, expression: "wash the dishes", forms: { present: "wash the dishes", third: "washes the dishes", past: "washed the dishes", pastParticiple: "washed the dishes", ing: "washing the dishes" },
    visualization: "You have used dishes and wash them in the sink.",
    interpretation: "Lavar los platos.", example: "I wash the dishes right after dinner.",
    category: "house", difficulty: "easy" },
  { id: 40, expression: "make the bed", forms: { present: "make the bed", third: "makes the bed", past: "made the bed", pastParticiple: "made the bed", ing: "making the bed" },
    visualization: "You arrange the sheets, pillows and blankets so the bed looks neat.",
    interpretation: "Tender la cama.", example: "I make the bed as soon as I get up.",
    category: "house", difficulty: "easy" },

  // ===================== MOVING AROUND (41-60) =====================
  { id: 41, expression: "go out", forms: { present: "go out", third: "goes out", past: "went out", pastParticiple: "gone out", ing: "going out" },
    visualization: "You leave your home or current place and go somewhere else.",
    interpretation: "Salir.", example: "We go out for dinner on Fridays.",
    category: "moving", difficulty: "easy" },
  { id: 42, expression: "come in", forms: { present: "come in", third: "comes in", past: "came in", pastParticiple: "come in", ing: "coming in" },
    visualization: "Someone is outside and enters the place where you are.",
    interpretation: "Entrar.", example: "Come in, the door is open.",
    category: "moving", difficulty: "easy" },
  { id: 43, expression: "go back", forms: { present: "go back", third: "goes back", past: "went back", pastParticiple: "gone back", ing: "going back" },
    visualization: "You're somewhere else and return to the place you were before.",
    interpretation: "Regresar / volver.", example: "I forgot my phone, so I went back home.",
    category: "moving", difficulty: "easy" },
  { id: 44, expression: "come back", forms: { present: "come back", third: "comes back", past: "came back", pastParticiple: "come back", ing: "coming back" },
    visualization: "Someone left and later returns to where you are.",
    interpretation: "Volver / regresar.", example: "I'll come back in ten minutes.",
    category: "moving", difficulty: "easy" },
  { id: 45, expression: "go ahead", forms: { present: "go ahead", third: "goes ahead", past: "went ahead", pastParticiple: "gone ahead", ing: "going ahead" },
    visualization: "Someone is waiting and you tell them they can continue.",
    interpretation: "Adelante / seguir adelante.", example: "Go ahead, I'll catch up with you.",
    category: "moving", difficulty: "medium" },
  { id: 46, expression: "come over", forms: { present: "come over", third: "comes over", past: "came over", pastParticiple: "come over", ing: "coming over" },
    visualization: "A person leaves where they are and comes to your house or location.",
    interpretation: "Venir a donde estoy / venir a mi casa.", example: "Can you come over after work?",
    category: "moving", difficulty: "medium" },
  { id: 47, expression: "get in", forms: { present: "get in", third: "gets in", past: "got in", pastParticiple: "gotten in", ing: "getting in" },
    visualization: "You open the door of a car and enter it.",
    interpretation: "Subirse (a un carro).", example: "Get in, I'll give you a ride.",
    category: "moving", difficulty: "easy" },
  { id: 48, expression: "get out", forms: { present: "get out", third: "gets out", past: "got out", pastParticiple: "gotten out", ing: "getting out" },
    visualization: "You open the car door and leave the vehicle.",
    interpretation: "Bajarse (de un carro).", example: "We got out of the car and walked inside.",
    category: "moving", difficulty: "easy" },
  { id: 49, expression: "get on", forms: { present: "get on", third: "gets on", past: "got on", pastParticiple: "gotten on", ing: "getting on" },
    visualization: "You step onto a bus, train, plane or another form of transportation.",
    interpretation: "Subirse (a un bus, tren, avión).", example: "I get on the bus at 6:45.",
    category: "moving", difficulty: "medium" },
  { id: 50, expression: "get off", forms: { present: "get off", third: "gets off", past: "got off", pastParticiple: "gotten off", ing: "getting off" },
    visualization: "You leave a bus, train, plane or another form of transportation.",
    interpretation: "Bajarse (de un bus, tren, avión).", example: "I get off at the next stop.",
    category: "moving", difficulty: "medium" },
  { id: 51, expression: "walk around", forms: { present: "walk around", third: "walks around", past: "walked around", pastParticiple: "walked around", ing: "walking around" },
    visualization: "You walk around an area without necessarily going directly to one specific destination.",
    interpretation: "Caminar por / dar vueltas.", example: "We walked around downtown all afternoon.",
    category: "moving", difficulty: "medium" },
  { id: 52, expression: "sit down", forms: { present: "sit down", third: "sits down", past: "sat down", pastParticiple: "sat down", ing: "sitting down" },
    visualization: "You're standing and lower your body until you're sitting.",
    interpretation: "Sentarse.", example: "Please sit down and make yourself comfortable.",
    category: "moving", difficulty: "easy" },
  { id: 53, expression: "stand up", forms: { present: "stand up", third: "stands up", past: "stood up", pastParticiple: "stood up", ing: "standing up" },
    visualization: "You're sitting and raise your body until you're standing.",
    interpretation: "Ponerse de pie / pararse.", example: "Everyone stood up when she walked in.",
    category: "moving", difficulty: "easy" },
  { id: 54, expression: "wait for me", forms: { present: "wait for me", third: "waits for me", past: "waited for me", pastParticiple: "waited for me", ing: "waiting for me" },
    visualization: "You're walking and ask someone to stop until you catch up.",
    interpretation: "Espérame.", example: "Wait for me, I'm almost there!",
    category: "moving", difficulty: "easy" },
  { id: 55, expression: "hurry up", forms: { present: "hurry up", third: "hurries up", past: "hurried up", pastParticiple: "hurried up", ing: "hurrying up" },
    visualization: "Someone is taking too long and you want them to move faster.",
    interpretation: "Apúrate.", example: "Hurry up, we're going to be late!",
    category: "moving", difficulty: "medium" },
  { id: 56, expression: "slow down", forms: { present: "slow down", third: "slows down", past: "slowed down", pastParticiple: "slowed down", ing: "slowing down" },
    visualization: "Someone is moving too fast and you want them to reduce their speed.",
    interpretation: "Ve más despacio.", example: "Slow down, this road is dangerous.",
    category: "moving", difficulty: "medium" },
  { id: 57, expression: "watch out", forms: { present: "watch out", third: "watches out", past: "watched out", pastParticiple: "watched out", ing: "watching out" },
    visualization: "You notice danger and quickly warn someone.",
    interpretation: "Cuidado.", example: "Watch out! There's a car coming.",
    category: "moving", difficulty: "medium" },
  { id: 58, expression: "move over", forms: { present: "move over", third: "moves over", past: "moved over", pastParticiple: "moved over", ing: "moving over" },
    visualization: "There isn't enough space and you ask someone to move to the side.",
    interpretation: "Hazte a un lado.", example: "Can you move over so I can sit down?",
    category: "moving", difficulty: "medium" },
  { id: 59, expression: "follow me", forms: { present: "follow me", third: "follows me", past: "followed me", pastParticiple: "followed me", ing: "following me" },
    visualization: "You walk ahead and want someone to come with you.",
    interpretation: "Sígueme.", example: "Follow me, I know a shortcut.",
    category: "moving", difficulty: "easy" },
  { id: 60, expression: "stay here", forms: { present: "stay here", third: "stays here", past: "stayed here", pastParticiple: "stayed here", ing: "staying here" },
    visualization: "You're in a place and want the other person to remain there.",
    interpretation: "Quédate aquí.", example: "Stay here, I'll be right back.",
    category: "moving", difficulty: "easy" },

  // ===================== FOOD & DAILY LIFE (61-70) =====================
  { id: 61, expression: "have lunch", forms: { present: "have lunch", third: "has lunch", past: "had lunch", pastParticiple: "had lunch", ing: "having lunch" },
    visualization: "You sit down and eat your meal around the middle of the day.",
    interpretation: "Almorzar.", example: "I have lunch at noon most days.",
    category: "food", difficulty: "easy" },
  { id: 62, expression: "have dinner", forms: { present: "have dinner", third: "has dinner", past: "had dinner", pastParticiple: "had dinner", ing: "having dinner" },
    visualization: "You sit down and eat your evening meal.",
    interpretation: "Cenar.", example: "We usually have dinner around 7.",
    category: "food", difficulty: "easy" },
  { id: 63, expression: "grab a bite", forms: { present: "grab a bite", third: "grabs a bite", past: "grabbed a bite", pastParticiple: "grabbed a bite", ing: "grabbing a bite" },
    visualization: "You're busy but stop briefly to eat something.",
    interpretation: "Comer algo rápido.", example: "Let's grab a bite before the movie.",
    category: "food", difficulty: "medium" },
  { id: 64, expression: "grab a snack", forms: { present: "grab a snack", third: "grabs a snack", past: "grabbed a snack", pastParticiple: "grabbed a snack", ing: "grabbing a snack" },
    visualization: "You quickly get something small to eat between meals.",
    interpretation: "Comer un bocadillo rápido.", example: "I grabbed a snack before the meeting.",
    category: "food", difficulty: "medium" },
  { id: 65, expression: "eat out", forms: { present: "eat out", third: "eats out", past: "ate out", pastParticiple: "eaten out", ing: "eating out" },
    visualization: "Instead of eating at home, you go somewhere like a restaurant to eat.",
    interpretation: "Comer fuera / salir a comer.", example: "We eat out once a week.",
    category: "food", difficulty: "medium" },
  { id: 66, expression: "order food", forms: { present: "order food", third: "orders food", past: "ordered food", pastParticiple: "ordered food", ing: "ordering food" },
    visualization: "You look at a menu and tell someone what food you want.",
    interpretation: "Pedir comida.", example: "We ordered food through an app.",
    category: "food", difficulty: "easy" },
  { id: 67, expression: "pay for it", forms: { present: "pay for it", third: "pays for it", past: "paid for it", pastParticiple: "paid for it", ing: "paying for it" },
    visualization: "You use cash, a card or your phone to pay for something.",
    interpretation: "Pagar por algo.", example: "Don't worry, I'll pay for it.",
    category: "food", difficulty: "easy" },
  { id: 68, expression: "drink up", forms: { present: "drink up", third: "drinks up", past: "drank up", pastParticiple: "drunk up", ing: "drinking up" },
    visualization: "You have a drink and finish all of it.",
    interpretation: "Terminarse la bebida.", example: "Drink up, we need to go soon.",
    category: "food", difficulty: "advanced" },
  { id: 69, expression: "fill it up", forms: { present: "fill it up", third: "fills it up", past: "filled it up", pastParticiple: "filled it up", ing: "filling it up" },
    visualization: "A container is empty or partly empty and you add more until it is full.",
    interpretation: "Llenarlo.", example: "Can you fill it up with water, please?",
    category: "food", difficulty: "medium" },
  { id: 70, expression: "cut it up", forms: { present: "cut it up", third: "cuts it up", past: "cut it up", pastParticiple: "cut it up", ing: "cutting it up" },
    visualization: "You take food and cut it into smaller pieces.",
    interpretation: "Cortarlo en pedazos.", example: "I cut it up before I cooked it.",
    category: "food", difficulty: "medium" },

  // ===================== WORK & SCHOOL (71-80) =====================
  { id: 71, expression: "go to work", forms: { present: "go to work", third: "goes to work", past: "went to work", pastParticiple: "gone to work", ing: "going to work" },
    visualization: "You leave home and travel toward your workplace.",
    interpretation: "Ir al trabajo.", example: "I go to work by bus.",
    category: "work", difficulty: "easy" },
  { id: 72, expression: "get to work", forms: { present: "get to work", third: "gets to work", past: "got to work", pastParticiple: "gotten to work", ing: "getting to work" },
    visualization: "You arrive at the place where you work.",
    interpretation: "Llegar al trabajo.", example: "I get to work at 8 sharp.",
    category: "work", difficulty: "easy" },
  { id: 73, expression: "go to school", forms: { present: "go to school", third: "goes to school", past: "went to school", pastParticiple: "gone to school", ing: "going to school" },
    visualization: "You leave home and travel toward the place where you study.",
    interpretation: "Ir a la escuela.", example: "My kids go to school in the morning.",
    category: "work", difficulty: "easy" },
  { id: 74, expression: "get to school", forms: { present: "get to school", third: "gets to school", past: "got to school", pastParticiple: "gotten to school", ing: "getting to school" },
    visualization: "You arrive at school.",
    interpretation: "Llegar a la escuela.", example: "She gets to school before everyone else.",
    category: "work", difficulty: "easy" },
  { id: 75, expression: "get started", forms: { present: "get started", third: "gets started", past: "got started", pastParticiple: "gotten started", ing: "getting started" },
    visualization: "You are ready to begin an activity and start doing it.",
    interpretation: "Empezar / comenzar.", example: "Let's get started on the project.",
    category: "work", difficulty: "medium" },
  { id: 76, expression: "take a break", forms: { present: "take a break", third: "takes a break", past: "took a break", pastParticiple: "taken a break", ing: "taking a break" },
    visualization: "You stop working or studying for a short time to rest.",
    interpretation: "Tomar un descanso.", example: "I always take a break at 10.",
    category: "work", difficulty: "easy" },
  { id: 77, expression: "get back to work", forms: { present: "get back to work", third: "gets back to work", past: "got back to work", pastParticiple: "gotten back to work", ing: "getting back to work" },
    visualization: "You finished your break and return to your work.",
    interpretation: "Volver al trabajo.", example: "Break's over, let's get back to work.",
    category: "work", difficulty: "medium" },
  { id: 78, expression: "finish up", forms: { present: "finish up", third: "finishes up", past: "finished up", pastParticiple: "finished up", ing: "finishing up" },
    visualization: "You're almost finished and are doing the last few things.",
    interpretation: "Terminar / rematar.", example: "I'm finishing up this report right now.",
    category: "work", difficulty: "medium" },
  { id: 79, expression: "fill out", forms: { present: "fill out", third: "fills out", past: "filled out", pastParticiple: "filled out", ing: "filling out" },
    visualization: "You have a form and write the required information in the empty spaces.",
    interpretation: "Llenar un formulario.", example: "Please fill out this form before your appointment.",
    category: "work", difficulty: "medium" },
  { id: 80, expression: "write it down", forms: { present: "write it down", third: "writes it down", past: "wrote it down", pastParticiple: "written it down", ing: "writing it down" },
    visualization: "Someone gives you information and you write it on paper or your phone so you don't forget it.",
    interpretation: "Anotarlo.", example: "Write it down so you don't forget.",
    category: "work", difficulty: "medium" },

  // ===================== EVERYDAY CONVERSATION (81-90) =====================
  { id: 81, expression: "hang out", forms: { present: "hang out", third: "hangs out", past: "hung out", pastParticiple: "hung out", ing: "hanging out" },
    visualization: "You're spending relaxed, informal time with friends without a specific activity or goal.",
    interpretation: "Pasar el rato / pasar tiempo con alguien.", example: "We hung out at my place all weekend.",
    category: "conversation", difficulty: "advanced" },
  { id: 82, expression: "catch up", forms: { present: "catch up", third: "catches up", past: "caught up", pastParticiple: "caught up", ing: "catching up" },
    visualization: "You haven't seen someone for a while, so you talk and tell each other what's been happening.",
    interpretation: "Ponerse al día.", example: "We caught up over coffee last week.",
    category: "conversation", difficulty: "advanced" },
  { id: 83, expression: "call me back", forms: { present: "call me back", third: "calls me back", past: "called me back", pastParticiple: "called me back", ing: "calling me back" },
    visualization: "You called someone but they didn't answer, so you want them to return your call later.",
    interpretation: "Devuélveme la llamada.", example: "Call me back when you get this.",
    category: "conversation", difficulty: "medium" },
  { id: 84, expression: "text me", forms: { present: "text me", third: "texts me", past: "texted me", pastParticiple: "texted me", ing: "texting me" },
    visualization: "You want someone to send you a message on their phone.",
    interpretation: "Escríbeme (mensaje de texto).", example: "Text me when you arrive.",
    category: "conversation", difficulty: "easy" },
  { id: 85, expression: "let me know", forms: { present: "let me know", third: "lets me know", past: "let me know", pastParticiple: "let me know", ing: "letting me know" },
    visualization: "You don't need an answer immediately; you want the person to tell you later.",
    interpretation: "Avísame.", example: "Let me know if you need anything.",
    category: "conversation", difficulty: "medium" },
  { id: 86, expression: "hold on", forms: { present: "hold on", third: "holds on", past: "held on", pastParticiple: "held on", ing: "holding on" },
    visualization: "You're talking to someone and ask them to wait for a moment.",
    interpretation: "Espera un momento.", example: "Hold on, let me check my calendar.",
    category: "conversation", difficulty: "medium" },
  { id: 87, expression: "hang on", forms: { present: "hang on", third: "hangs on", past: "hung on", pastParticiple: "hung on", ing: "hanging on" },
    visualization: "You're doing something and ask the other person to wait briefly.",
    interpretation: "Espera un momento.", example: "Hang on, I'm almost done.",
    category: "conversation", difficulty: "medium" },
  { id: 88, expression: "give me a hand", forms: { present: "give me a hand", third: "gives me a hand", past: "gave me a hand", pastParticiple: "given me a hand", ing: "giving me a hand" },
    visualization: "You're having trouble with something and ask someone to help you.",
    interpretation: "Échame una mano / ayúdame.", example: "Can you give me a hand with these bags?",
    category: "conversation", difficulty: "advanced" },
  { id: 89, expression: "give me a second", forms: { present: "give me a second", third: "gives me a second", past: "gave me a second", pastParticiple: "given me a second", ing: "giving me a second" },
    visualization: "You need a few seconds before you answer or do something.",
    interpretation: "Dame un segundo.", example: "Give me a second, I need to think about it.",
    category: "conversation", difficulty: "medium" },
  { id: 90, expression: "come on", forms: { present: "come on", third: "comes on", past: "came on", pastParticiple: "come on", ing: "coming on" },
    visualization: "You want someone to move, continue, hurry, encourage themselves, or stop doing something.",
    interpretation: "Vamos / ándale / ¡ay, por favor!", example: "Come on, we're going to miss the bus!",
    category: "conversation", difficulty: "advanced" },

  // ===================== VERY NATURAL EVERYDAY ENGLISH (91-100) =====================
  { id: 91, expression: "figure it out", forms: { present: "figure it out", third: "figures it out", past: "figured it out", pastParticiple: "figured it out", ing: "figuring it out" },
    visualization: "You don't know how to solve something, so you think about it until you find the solution.",
    interpretation: "Encontrar la solución / resolverlo.", example: "Don't worry, we'll figure it out together.",
    category: "natural", difficulty: "advanced" },
  { id: 92, expression: "find out", forms: { present: "find out", third: "finds out", past: "found out", pastParticiple: "found out", ing: "finding out" },
    visualization: "You don't know some information and do something to discover it.",
    interpretation: "Averiguar / descubrir.", example: "I just found out I got the job.",
    category: "natural", difficulty: "medium" },
  { id: 93, expression: "look for", forms: { present: "look for", third: "looks for", past: "looked for", pastParticiple: "looked for", ing: "looking for" },
    visualization: "You don't know where something is, so you search different places for it.",
    interpretation: "Buscar algo.", example: "I'm looking for my keys.",
    category: "natural", difficulty: "medium" },
  { id: 94, expression: "look at", forms: { present: "look at", third: "looks at", past: "looked at", pastParticiple: "looked at", ing: "looking at" },
    visualization: "Something is in front of you and you direct your eyes toward it.",
    interpretation: "Mirar algo.", example: "Look at this picture I took yesterday.",
    category: "natural", difficulty: "easy" },
  { id: 95, expression: "look out", forms: { present: "look out", third: "looks out", past: "looked out", pastParticiple: "looked out", ing: "looking out" },
    visualization: "There is possible danger and you warn someone to be careful.",
    interpretation: "Cuidado / ojo.", example: "Look out! The floor is wet.",
    category: "natural", difficulty: "advanced" },
  { id: 96, expression: "check it out", forms: { present: "check it out", third: "checks it out", past: "checked it out", pastParticiple: "checked it out", ing: "checking it out" },
    visualization: "You notice something interesting and want someone to look at it or experience it.",
    interpretation: "Échale un ojo / míralo.", example: "I found a new restaurant, you should check it out.",
    category: "natural", difficulty: "advanced" },
  { id: 97, expression: "try it out", forms: { present: "try it out", third: "tries it out", past: "tried it out", pastParticiple: "tried it out", ing: "trying it out" },
    visualization: "You have something new and use it to see how it works.",
    interpretation: "Probarlo.", example: "I got a new app, so I tried it out today.",
    category: "natural", difficulty: "medium" },
  { id: 98, expression: "run out of", forms: { present: "run out of", third: "runs out of", past: "ran out of", pastParticiple: "run out of", ing: "running out of" },
    visualization: "You had something, used it little by little, and eventually there is none left.",
    interpretation: "Quedarse sin algo.", example: "We ran out of coffee this morning.",
    category: "natural", difficulty: "advanced" },
  { id: 99, expression: "run into", forms: { present: "run into", third: "runs into", past: "ran into", pastParticiple: "run into", ing: "running into" },
    visualization: "You're going about your day and unexpectedly meet someone or encounter a problem.",
    interpretation: "Encontrarse con alguien por casualidad.", example: "I ran into my old teacher at the store.",
    category: "natural", difficulty: "advanced" },
  { id: 100, expression: "keep going", forms: { present: "keep going", third: "keeps going", past: "kept going", pastParticiple: "kept going", ing: "keeping going" },
    visualization: "You're doing something difficult or tiring but continue instead of stopping.",
    interpretation: "Seguir adelante / continuar.", example: "It's hard, but you have to keep going.",
    category: "natural", difficulty: "medium" }
];

/* Personal "Think in English" prompts keyed by expression id (fallback generated if absent) */
const PERSONAL_PROMPTS = {
  1: "What time do you wake up on weekdays?",
  2: "What time do you get up?",
  17: "Do you usually grab a coffee in the morning?",
  40: "Do you make your bed every day?",
  65: "How often do you eat out?",
  76: "When do you usually take a break?",
  81: "Who do you usually hang out with?",
  82: "Who do you need to catch up with?",
  93: "What's something you're currently looking for?",
  98: "What do you often run out of at home?"
};

if (typeof module !== "undefined") {
  module.exports = { CATEGORIES, EXPRESSIONS, PERSONAL_PROMPTS };
}
