/* =========================================================
   VERBS-DATA.JS — Banco de verbos para el juego de Memoria
   NicaEnglish Club · 100 verbos base más comunes del inglés
   americano, cada uno con su significado en español.
   El juego elige pares al azar de esta lista cada partida.
   ========================================================= */

export const VERBS = [
  { en: "be", es: "ser / estar" },
  { en: "have", es: "tener" },
  { en: "do", es: "hacer" },
  { en: "say", es: "decir" },
  { en: "go", es: "ir" },
  { en: "get", es: "obtener / conseguir" },
  { en: "make", es: "hacer / fabricar" },
  { en: "know", es: "saber / conocer" },
  { en: "think", es: "pensar" },
  { en: "take", es: "tomar" },
  { en: "see", es: "ver" },
  { en: "come", es: "venir" },
  { en: "want", es: "querer" },
  { en: "look", es: "mirar" },
  { en: "use", es: "usar" },
  { en: "find", es: "encontrar" },
  { en: "give", es: "dar" },
  { en: "tell", es: "decir / contar" },
  { en: "work", es: "trabajar" },
  { en: "call", es: "llamar" },
  { en: "try", es: "intentar" },
  { en: "ask", es: "preguntar / pedir" },
  { en: "need", es: "necesitar" },
  { en: "feel", es: "sentir" },
  { en: "become", es: "convertirse" },
  { en: "leave", es: "dejar / salir" },
  { en: "put", es: "poner" },
  { en: "mean", es: "significar" },
  { en: "keep", es: "mantener / guardar" },
  { en: "let", es: "dejar / permitir" },
  { en: "begin", es: "comenzar" },
  { en: "seem", es: "parecer" },
  { en: "help", es: "ayudar" },
  { en: "talk", es: "hablar / platicar" },
  { en: "turn", es: "girar / voltear" },
  { en: "start", es: "empezar" },
  { en: "show", es: "mostrar" },
  { en: "hear", es: "oír" },
  { en: "play", es: "jugar / tocar" },
  { en: "run", es: "correr" },
  { en: "move", es: "mover / mudarse" },
  { en: "like", es: "gustar" },
  { en: "live", es: "vivir" },
  { en: "believe", es: "creer" },
  { en: "bring", es: "traer" },
  { en: "happen", es: "suceder / pasar" },
  { en: "write", es: "escribir" },
  { en: "provide", es: "proporcionar" },
  { en: "sit", es: "sentarse" },
  { en: "stand", es: "pararse / estar de pie" },
  { en: "lose", es: "perder" },
  { en: "pay", es: "pagar" },
  { en: "meet", es: "conocer / reunirse" },
  { en: "include", es: "incluir" },
  { en: "continue", es: "continuar" },
  { en: "set", es: "establecer / poner" },
  { en: "learn", es: "aprender" },
  { en: "change", es: "cambiar" },
  { en: "lead", es: "liderar / guiar" },
  { en: "understand", es: "entender" },
  { en: "watch", es: "observar / mirar" },
  { en: "follow", es: "seguir" },
  { en: "stop", es: "detener / parar" },
  { en: "create", es: "crear" },
  { en: "speak", es: "hablar" },
  { en: "read", es: "leer" },
  { en: "allow", es: "permitir" },
  { en: "add", es: "agregar / añadir" },
  { en: "spend", es: "gastar" },
  { en: "grow", es: "crecer" },
  { en: "open", es: "abrir" },
  { en: "walk", es: "caminar" },
  { en: "win", es: "ganar" },
  { en: "offer", es: "ofrecer" },
  { en: "remember", es: "recordar" },
  { en: "love", es: "amar" },
  { en: "consider", es: "considerar" },
  { en: "appear", es: "aparecer" },
  { en: "buy", es: "comprar" },
  { en: "wait", es: "esperar" },
  { en: "serve", es: "servir" },
  { en: "die", es: "morir" },
  { en: "send", es: "enviar" },
  { en: "expect", es: "esperar / anticipar" },
  { en: "build", es: "construir" },
  { en: "stay", es: "quedarse" },
  { en: "fall", es: "caer" },
  { en: "cut", es: "cortar" },
  { en: "reach", es: "alcanzar / llegar a" },
  { en: "kill", es: "matar" },
  { en: "remain", es: "permanecer" },
  { en: "suggest", es: "sugerir" },
  { en: "raise", es: "levantar / criar" },
  { en: "pass", es: "pasar" },
  { en: "sell", es: "vender" },
  { en: "require", es: "requerir" },
  { en: "report", es: "informar / reportar" },
  { en: "decide", es: "decidir" },
  { en: "pull", es: "jalar / tirar de" },
  { en: "break", es: "romper" },
];
