/* =========================================================
   SENTENCES-DATA.JS — Banco de oraciones para Arma la Oración
   NicaEnglish Club · 100 oraciones en inglés americano.
   Cada entrada guarda la oración en el orden CORRECTO;
   el juego desordena las palabras al azar en cada partida.
   ========================================================= */

export const SENTENCES = [
  { words: ["I", "like", "to", "read", "books", "at", "night"] },
  { words: ["She", "goes", "to", "school", "every", "morning"] },
  { words: ["We", "are", "having", "dinner", "right", "now"] },
  { words: ["He", "can", "speak", "three", "languages"] },
  { words: ["They", "play", "soccer", "on", "weekends"] },
  { words: ["My", "mother", "cooks", "delicious", "food"] },
  { words: ["The", "dog", "is", "sleeping", "on", "the", "couch"] },
  { words: ["I", "need", "to", "buy", "some", "milk"] },
  { words: ["Can", "you", "help", "me", "with", "this"] },
  { words: ["She", "works", "at", "a", "hospital", "downtown"] },
  { words: ["We", "watched", "a", "movie", "last", "night"] },
  { words: ["He", "always", "arrives", "early", "to", "class"] },
  { words: ["I", "am", "learning", "English", "this", "year"] },
  { words: ["The", "children", "are", "playing", "in", "the", "park"] },
  { words: ["Please", "close", "the", "door", "behind", "you"] },
  { words: ["My", "father", "drives", "a", "red", "truck"] },
  { words: ["They", "live", "in", "a", "small", "apartment"] },
  { words: ["I", "usually", "drink", "coffee", "in", "the", "morning"] },
  { words: ["She", "wants", "to", "travel", "around", "the", "world"] },
  { words: ["We", "need", "to", "leave", "in", "ten", "minutes"] },
  { words: ["He", "forgot", "his", "keys", "at", "home"] },
  { words: ["I", "will", "call", "you", "after", "work"] },
  { words: ["The", "store", "closes", "at", "nine", "tonight"] },
  { words: ["She", "is", "wearing", "a", "blue", "dress", "today"] },
  { words: ["We", "should", "study", "for", "the", "exam"] },
  { words: ["He", "bought", "a", "new", "phone", "yesterday"] },
  { words: ["I", "can", "not", "find", "my", "glasses"] },
  { words: ["They", "are", "waiting", "for", "the", "bus"] },
  { words: ["My", "sister", "loves", "to", "paint", "pictures"] },
  { words: ["We", "walked", "to", "the", "beach", "this", "afternoon"] },
  { words: ["He", "never", "eats", "breakfast", "in", "the", "morning"] },
  { words: ["I", "have", "to", "finish", "my", "homework", "tonight"] },
  { words: ["She", "sings", "very", "well", "in", "the", "choir"] },
  { words: ["The", "teacher", "explained", "the", "lesson", "clearly"] },
  { words: ["We", "are", "going", "to", "the", "market", "now"] },
  { words: ["He", "runs", "five", "miles", "every", "day"] },
  { words: ["I", "forgot", "to", "turn", "off", "the", "lights"] },
  { words: ["They", "built", "a", "new", "house", "last", "year"] },
  { words: ["She", "always", "helps", "her", "neighbors", "kindly"] },
  { words: ["We", "should", "try", "that", "new", "restaurant"] },
  { words: ["He", "is", "reading", "a", "mystery", "novel"] },
  { words: ["I", "hope", "you", "feel", "better", "soon"] },
  { words: ["The", "train", "arrives", "at", "six", "o", "clock"] },
  { words: ["She", "decided", "to", "change", "her", "job"] },
  { words: ["We", "spent", "the", "whole", "day", "at", "home"] },
  { words: ["He", "carried", "the", "boxes", "upstairs", "alone"] },
  { words: ["I", "remember", "meeting", "you", "last", "summer"] },
  { words: ["They", "sell", "fresh", "fruit", "at", "the", "market"] },
  { words: ["She", "continues", "to", "study", "every", "night"] },
  { words: ["We", "followed", "the", "map", "to", "the", "hotel"] },
  { words: ["He", "stopped", "the", "car", "at", "the", "light"] },
  { words: ["I", "created", "a", "new", "plan", "for", "us"] },
  { words: ["She", "speaks", "softly", "to", "the", "baby"] },
  { words: ["We", "added", "more", "salt", "to", "the", "soup"] },
  { words: ["He", "grew", "up", "in", "a", "small", "town"] },
  { words: ["I", "opened", "the", "window", "for", "fresh", "air"] },
  { words: ["They", "won", "the", "game", "in", "the", "end"] },
  { words: ["She", "offered", "me", "a", "cup", "of", "tea"] },
  { words: ["We", "considered", "moving", "to", "another", "city"] },
  { words: ["He", "appeared", "happy", "at", "the", "party"] },
  { words: ["I", "waited", "for", "her", "outside", "the", "store"] },
  { words: ["She", "served", "dinner", "to", "all", "the", "guests"] },
  { words: ["We", "drove", "through", "the", "mountains", "together"] },
  { words: ["He", "raised", "his", "hand", "to", "answer"] },
  { words: ["I", "passed", "the", "test", "with", "a", "good", "grade"] },
  { words: ["They", "required", "more", "time", "to", "finish"] },
  { words: ["She", "reported", "the", "accident", "to", "the", "police"] },
  { words: ["We", "pulled", "the", "boat", "onto", "the", "sand"] },
  { words: ["He", "broke", "his", "arm", "playing", "basketball"] },
  { words: ["I", "explained", "the", "problem", "to", "my", "boss"] },
  { words: ["She", "developed", "a", "new", "recipe", "for", "cake"] },
  { words: ["We", "stayed", "at", "a", "small", "hotel", "nearby"] },
  { words: ["He", "fell", "asleep", "during", "the", "movie"] },
  { words: ["I", "cut", "the", "vegetables", "for", "the", "salad"] },
  { words: ["They", "reached", "the", "top", "of", "the", "mountain"] },
  { words: ["She", "remained", "calm", "during", "the", "storm"] },
  { words: ["We", "suggested", "a", "different", "plan", "to", "them"] },
  { words: ["He", "lost", "his", "wallet", "on", "the", "bus"] },
  { words: ["I", "paid", "the", "bill", "at", "the", "counter"] },
  { words: ["She", "met", "her", "best", "friend", "downtown"] },
  { words: ["We", "included", "everyone", "in", "the", "invitation"] },
  { words: ["He", "led", "the", "team", "to", "victory"] },
  { words: ["I", "understood", "the", "instructions", "perfectly"] },
  { words: ["They", "watched", "the", "sunset", "from", "the", "hill"] },
  { words: ["She", "learned", "to", "swim", "last", "summer"] },
  { words: ["We", "changed", "our", "plans", "at", "the", "last", "minute"] },
  { words: ["He", "believes", "in", "working", "hard", "every", "day"] },
  { words: ["I", "brought", "some", "snacks", "for", "the", "trip"] },
  { words: ["She", "writes", "letters", "to", "her", "grandmother"] },
  { words: ["We", "provided", "food", "for", "the", "whole", "event"] },
  { words: ["He", "sat", "quietly", "in", "the", "corner"] },
  { words: ["I", "stood", "there", "watching", "the", "parade"] },
  { words: ["They", "talked", "about", "their", "favorite", "movies"] },
  { words: ["She", "turned", "the", "music", "down", "softly"] },
  { words: ["We", "started", "the", "meeting", "on", "time"] },
  { words: ["He", "showed", "me", "his", "new", "apartment"] },
  { words: ["I", "heard", "a", "strange", "noise", "outside"] },
  { words: ["She", "kept", "her", "promise", "to", "visit"] },
  { words: ["We", "began", "the", "project", "last", "week"] },
  { words: ["He", "seemed", "nervous", "before", "the", "interview"] },
];
